spring:
  application:
    name: Student-App

  datasource:
    url: jdbc:mysql://localhost:3306/harikumar
    username: root
    password: system
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 5555